
build:
	poetry build

publish:
	poetry publish

install:
	poetry install

#.PHONY: gendiff
gendiff:
	poetry run gendiff

test-coverage:
	poetry run pytest --cov=gendiff --cov-report xml

lint:
	poetry run flake8 gendiff

