name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip pytest flake8 poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install flake8
          pip install poetry
      - name: Test with pytest
        run: |
          make test-coverage
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.11.0-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter 
          ./cc-test-reporter before-build
      - name: Sending Repo
        env:
          GITHAB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
        run:  |
         ./cc-test-reporter after-build -r $GITHAB_TOKEN
      - name: Test with flake8
        run: |
          make lint
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
